# Generated by Django 6.0.1 on 2026-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='bonus_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonus amount per day if 0 leaves in month', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Or bonus as % of basic (if per_day=0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='default_working_days',
            field=models.PositiveIntegerField(default=26, help_text='Default working days per month'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='fuel_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fuel allowance % of basic', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='housing_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Housing allowance % of basic', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='late_deduction_per',
            field=models.PositiveIntegerField(default=3, help_text='Late days count as 1 half-day deduct'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='max_allowed_leaves',
            field=models.PositiveIntegerField(default=0, help_text='Max paid leaves per month'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='medical_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Medical allowance % of basic', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='provident_fund_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PF % of basic', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='transport_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport allowance % of basic', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax % deducted from gross', max_digits=5),
        ),
    ]
