# Generated by Django 6.0.1 on 2026-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_salaryconfig_bonus_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours this month', max_digits=6),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate per hour', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.PositiveIntegerField(default=0, help_text='Paid leaves (no salary deduction)'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='unpaid_leaves',
            field=models.PositiveIntegerField(default=0, help_text='Unpaid leaves (salary deducted)'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='allowed_leaves',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated from config'),
        ),
    ]
