# Generated by Django 6.0.1 on 2026-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_monthlysalary_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='month',
            field=models.PositiveIntegerField(default=1, help_text='Month (1-12)'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Year'),
        ),
    ]
