# Generated by Django 6.0.2 on 2026-03-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_parentprofile_user_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
