# Generated by Django 6.0.1 on 2026-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_class_school_parentprofile_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cnic',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('vp', 'VP'), ('group_head', 'Group Head')], default='teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
