# Generated by Django 6.0.1 on 2026-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_teacherprofile_cnic_teacherprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('daily_wager', 'Daily Wager')], default='permanent', max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_employee_separated',
            field=models.BooleanField(default=False, help_text='Has the employee left?'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basic Monthly/Daily Salary', max_digits=12),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('permanent_professional', 'Permanent Professional'), ('skilled', 'Skilled'), ('semi_skilled', 'Semi Skilled'), ('unskilled', 'Unskilled')], default='permanent_professional', max_length=25),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='working_days_per_week',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('vp', 'VP'), ('group_head', 'Group Head')], default='teacher', max_length=25),
        ),
    ]
